# Build-time asset packer, run as `cmake -P`. Concatenates every asset behind an ASCII table of
# contents, compresses the result with the host xz, and writes the uncompressed length out as a
# header so the decompressor can size its buffer in one shot. The archive layout is documented in
# src/assets/assets_embedded.cpp — change both together.
#
# Inputs (all -D):
#   MANIFEST     file of "name=path" lines, one per asset; `name` is what load() takes
#   ARCHIVE      output .xz path
#   SIZE_HEADER  output header path, defines vkhb::assets::detail::kArchiveBytes
#   XZ           host xz executable
#   STAGE_DIR    scratch directory for the uncompressed archive
#
# The manifest is a file rather than a -DASSETS= list because CMake list separators do not survive
# a trip through add_custom_command's argument quoting intact.

foreach(required MANIFEST ARCHIVE SIZE_HEADER XZ STAGE_DIR)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "PackAssets.cmake: -D${required}= is required")
  endif()
endforeach()

# --- Table of contents. Offsets are payload-relative, so the TOC's own length does not feed back
# into them; only the header line's fixed 8-digit width has to be respected.
set(toc_body "")
set(offset 0)
set(payload_files "")
file(STRINGS "${MANIFEST}" asset_entries)
foreach(entry IN LISTS asset_entries)
  if(NOT entry MATCHES "^([^=]+)=(.+)$")
    message(FATAL_ERROR "PackAssets.cmake: malformed asset entry '${entry}', expected name=path")
  endif()
  set(name "${CMAKE_MATCH_1}")
  set(path "${CMAKE_MATCH_2}")
  # The TOC separates its three fields with spaces, so a name holding one would silently produce an
  # archive the reader rejects wholesale. src/CMakeLists.txt catches this earlier and with better
  # advice; this is the format's own invariant, guarded where the format is written.
  if(name MATCHES "[ \t]")
    message(FATAL_ERROR "PackAssets.cmake: asset name '${name}' contains whitespace")
  endif()
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "PackAssets.cmake: asset '${name}' is missing at ${path}")
  endif()
  file(SIZE "${path}" size)
  string(APPEND toc_body "${name} ${offset} ${size}\n")
  math(EXPR offset "${offset} + ${size}")
  list(APPEND payload_files "${path}")
endforeach()

string(LENGTH "${toc_body}" toc_body_bytes)
math(EXPR toc_bytes "16 + ${toc_body_bytes}")  # 16 = "VKHBA1 " + 8 digits + newline
string(LENGTH "${toc_bytes}" digits)
if(digits GREATER 8)
  message(FATAL_ERROR "PackAssets.cmake: table of contents is too large for the 8-digit header")
endif()
math(EXPR pad "8 - ${digits}")
set(zeros "")
if(pad GREATER 0)
  string(REPEAT "0" ${pad} zeros)
endif()

file(MAKE_DIRECTORY "${STAGE_DIR}")
set(toc_file "${STAGE_DIR}/toc")
set(archive_raw "${STAGE_DIR}/vkhb_assets.bin")
file(WRITE "${toc_file}" "VKHBA1 ${zeros}${toc_bytes}\n${toc_body}")
# `cmake -E cat` rather than file(READ)/file(WRITE): the payload is binary, and CMake strings cannot
# carry embedded NULs.
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E cat "${toc_file}" ${payload_files}
  OUTPUT_FILE "${archive_raw}"
  RESULT_VARIABLE cat_result
  ERROR_VARIABLE cat_error
)
if(NOT cat_result EQUAL 0)
  message(FATAL_ERROR "PackAssets.cmake: concatenating assets failed (${cat_result}): ${cat_error}")
endif()

file(SIZE "${archive_raw}" archive_bytes)
file(WRITE "${SIZE_HEADER}"
  "// Generated by cmake/PackAssets.cmake. Do not edit.\n"
  "#pragma once\n"
  "#include <cstddef>\n"
  "namespace vkhb::assets::detail {\n"
  "inline constexpr std::size_t kArchiveBytes = ${archive_bytes};\n"
  "}  // namespace vkhb::assets::detail\n")

# --check=crc32 is not the xz default (crc64 is): xz-embedded always understands CRC32 but only
# supports CRC64 when built with XZ_USE_CRC64, which src/assets does not enable.
execute_process(
  COMMAND "${XZ}" --compress --format=xz --check=crc32 -9e --threads=1 --stdout "${archive_raw}"
  OUTPUT_FILE "${ARCHIVE}"
  RESULT_VARIABLE xz_result
  ERROR_VARIABLE xz_error
)
if(NOT xz_result EQUAL 0)
  message(FATAL_ERROR "PackAssets.cmake: xz failed (${xz_result}): ${xz_error}")
endif()

file(SIZE "${ARCHIVE}" compressed_bytes)
math(EXPR percent "100 * ${compressed_bytes} / ${archive_bytes}")
message(STATUS "Packed assets: ${archive_bytes} -> ${compressed_bytes} bytes (${percent}%)")
